hash-format = "sha256"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1502d3ac2c2ce4d3dc4c2db6ca6e95fb2a5d4a279e6e1413f6c427be222887a0"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "1da3968005c6c75dc95949cecd2a8b3e55bdb1e6f86a9fc0716380a56c473793"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "b6986c7bdec6840b8a344b4028b0a52be10460f2630223ca88db681b36cd5efa"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3d24d58b2caf4fd73d76b2d734a1d06490994d5d38177376e6f5d8d9f8fb87e0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0345fbfa8542b5ec84535fe2aff0f5cc4e801ecc337f926d4e2310b53f458569"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "e27ebce7267fbba8f0216424b21f041bc6c77a773d71848963c41d7a93e02c51"
metafile = true

[[files]]
file = "mods/gca.pw.toml"
hash = "ad6431ae85cda19cc94146ee1e2b9d35bf492804bd3381a55c018d8d52bec56e"
metafile = true

[[files]]
file = "mods/imblocker-original.pw.toml"
hash = "c4232b420082d36d454835f68e14da8c72e8f274e6b5b6c5c46e254d2f388fe7"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "db46aeba51086f72e755106ca1a2196717ddb3844dfd7b781e7a93c57a9d5b32"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "4105db403a4d910ac628d73a2cafdb9242d5f59c7b53e5b984fbb2fceb7cd3c5"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "fecd2e19a6afd8109bb6cfc281d158e3f7a5d6646a99340e2ece5d1aaece4edc"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "609e3cfdb2b7ece2eac05e99a23d538de490dc0b8e5a91155486714a3e813751"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "83fc77051e675c101fddb28ed303ce57deb4d26b58c025d4d9f60b2d1b37a5c1"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "6a9a36e5b6df0459227d4c67760fab573d363f43e252a071c139cc576ff15588"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "cb330220512be399e4423c39f01f56f8bc413f15b0b5a7fa8079699bcdd133bc"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "9946fd3c2a85099bb68cff8a2168601c3f1c7879fc42d018171c7cf5f25693d2"
metafile = true

[[files]]
file = "mods/mclogs.pw.toml"
hash = "a2d96f7777817783742832aee79dccbc64654445f262a39354efe1ac5b5ea6f1"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "9901b4a332af2554d61e1a0547a8d6dce114232ecc48f5b4512ab867c1d680ef"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6f9c7fd82681111859ff63446dc8327447adeaad84e9cfb534955afb5eb6c81a"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "ab6def9d98d3f5bf12f78845bdb770a19d5ca590c571e60184e537ffa14dcbee"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "9a0d53217201df1a02fd2c4db95b61136da9b94e734876fe63116f4811538ed5"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "50eb0e7f1524dec313a55ba1f70493fa3d01c0fb2167ce1d4f7554cc01b926b6"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "f51886499973a9a5c55c78d08c395e1c83af76ea7a560a0c88c91d973fe14246"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "22cff4ede67e4810127dfb952db897559bf64b000697dc78bf6b2b25eaedfb5c"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "b6637110509503de5c77ce30430a21a4d2570d33c8589087f9384eb04995ec3e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "361986055445d4bc51c04fef877501e7791ee361d3cccedced7344b17d70f8c4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "428c9b21e6c1cccaa18ab2afcba72b0bef30aa81cb392d8624699fe5934600b6"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "976682e613b79e310fe22c5ddc2322bfc76665295cd9fa885787dfa08b7764b2"
metafile = true
