name = "CJC"
author = "Chen Jicheng"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc4fdb45e71d1f5513f05568cc596a37ebdf8e577f2ba8aedf0d11f808e47fc6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
