name = "CJC"
author = "Chen Jicheng"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0502aa7280c41ccfce01a194f5d2ca5f5afe04cab3891b3ff920ac1348de186"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
